# Dockerfile.collector
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app

WORKDIR /wheels
COPY collector/requirements.collector.txt /wheels/requirements.txt
RUN pip install --no-cache-dir -r /wheels/requirements.txt

WORKDIR /app
COPY collector/ /app/collector/
COPY db/        /app/db/
COPY collector/entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

VOLUME ["/data"]

CMD ["/app/entrypoint.sh"]
